### ISSUE TITLE
Importer can't handle nested lists

### ISSUE THREAD

**Issue by corbanbrook** [icelab/draft-js-ast-importer#2]
This may be related to https://github.com/icelab/draft-js-ast-exporter/issues/3#event-768070940

ast-exporter correctly outputs the following structure, but ast-importer breaks on it with

`Uncaught TypeError: Cannot read property 'text' of undefined`

``` javascript
          // Build up block content
          var text = '';
          var characterList = (0, _immutable.List)();

          children.forEach(function (child) {
            var type = child[0];
            var childData = visit(child, { depth: depth + 1 });
            // Combine the text and the character list
            text = text + childData.text; // <------ childData undefined
            characterList = characterList.concat(childData.characterList);
          });
```

```
[
  "block",
  [
    "unordered-list-item",
    "7n69m",
    [
      [
        "inline",
        [
          [],
          "This is a nested list"
        ]
      ],
      [
        "block",
        [
          "unordered-list-item",
          "6umss",
          [
            [
              "inline",
              [
                [],
                "cool eh?"
              ]
            ]
          ]
        ]
      ]
    ]
  ]
]
```

**Comment by corbanbrook** [comment]
Part of the problem is that visitBlock doesnt return the contentBlock. It just pushes to a blocks array which seems to be used for root level blocks. When returning the contentBlock, it gets past the error i reported but then adds the block to the root level block map and causes other issues.

**Comment by makenosound** [comment]
@corbanbrook Have made a change I think will work, but haven’t had a chance to test yet (and might not for a few weeks). It’s up at https://github.com/icelab/draft-js-ast-importer/pull/3

**Comment by corbanbrook** [comment]
I will have some time today to look at it, already begun experimenting with a possible solution

**Comment by makenosound** [comment]
Fixed by @corbanbrook in https://github.com/icelab/draft-js-ast-importer/pull/4
